model:
  name: databricks-claude-3-7-sonnet
  parameters:
    max_tokens: 1500
    temperature: 0
langgraph:
  streaming: True
  
genie:                                 
  genie_space_id: "????????????????"    # fill in here

mlflow:
  experiment_location: "????????????????????"   # my experiment fill in here
  uc_model: main.default.????????????? # fill in here
  endpoint_name: databricks-claude-3-7-sonnet
